export const PUBLISH_PLAYER_NAMES = Symbol('PUBLISH_PLAYER_NAMES');
export const FETCH_PLAYER_NAMES = Symbol('FETCH_PLAYER_NAMES');
export const PUBLISH_BOARD_SPACES = Symbol('PUBLISH_BOARD_SPACES');
export const FETCH_BOARD_SPACES = Symbol('FETCH_BOARD_SPACES');